### ISSUE TITLE
BMP Report - Phragmities should be Phragmites

### ISSUE THREAD

**Issue by cstevenson1** [leeensminger/DelDOT-NPDES-Viewer#181]
Likely caused by bug 158 in the GitHub for the Field Tool. 

![image](https://user-images.githubusercontent.com/16919898/31510325-5b7cea34-af52-11e7-8b7c-dd9aae69037c.png)

![image](https://user-images.githubusercontent.com/16919898/31510353-738fc6aa-af52-11e7-9bec-1466cabe3abb.png)

**Comment by leeensminger** [comment]
See #158

**Comment by leeensminger** [comment]
Should be fixed with the fix of #158

**Comment by cstevenson1** [comment]
Fixed at bottom of report but not the top

Top
![image](https://user-images.githubusercontent.com/16919898/32371850-da2d8f2e-c068-11e7-9029-af1428596a60.png)

Bottom
![image](https://user-images.githubusercontent.com/16919898/32371694-3e5a295e-c068-11e7-9782-446548f5bcbd.png)

**Comment by leeensminger** [comment]
@gerrykelly prior to Christina's last comment, I updated values in dev/default BMP_INSPECTION_INVASIVES.INVASIVE_TYPE, and set all "Phragmites"-related values (there were several due to erroneous data) == 'Phragmites (Common Reed)'.  Not sure how that old value even could be brought in - thoughts?

**Comment by leeensminger** [comment]
Here's the db records for this inspection:
BMP_INSPECTIONS.GlobalID = {A8EFCEE8-C4CD-4B58-8D16-269757C1031D}
BMP 182
2017 inspection

![image](https://user-images.githubusercontent.com/4103847/32372882-21603014-c06d-11e7-8fe4-5eb25108e0b9.png)

**Comment by gerrykelly** [comment]
@leeensminger 
If there is a bad value that does not match a domain (or any bad value for that matter), the report will just show it as-is.  So this is a data issue and seems to have been fixed.

**Comment by leeensminger** [comment]
@gerrykelly The reports (like the viewer as a whole) is targeting the DEFAULT version - correct?

When I updated the INVASIVE_TYPE values, I did so in default - and that change is visible now in default.  The old value (bad spelling) still exists in the field version - and it appears that this is what is being pulled into that section of the report.  Again, it appears the DEFAULT data is being used in the _Minor Issues Not Affecting Performance_, so there appears to be a mismatch in the source version within the report.

**Comment by gerrykelly** [comment]
@leeensminger 
Gotcha.  Good catch.  Should be fixed now.  (and hopefully this only happened with BMP_INSPECTION_INVASIVES, since it gets specially handled in the code)

**Comment by cstevenson1** [comment]
Appears to be fine
![image](https://user-images.githubusercontent.com/16919898/32742568-d48f629c-c877-11e7-89a9-1e89e4170966.png)
![image](https://user-images.githubusercontent.com/16919898/32742590-e78fb82e-c877-11e7-849c-bb465e5e641e.png)
